#nexmoe主题的配置文件
avatar: /images/web_img/user_icon.png # 头像

# 文章默认封面
default_cover:
  path: /images/web_img/default_cover.jpeg
  width: 8000
  height: 4500

# # 博客的背景
background: 
  path: /images/web_img/web_background.jpg
  width: 8000
  height: 4500

favicon:
  href: /images/web_img/favicon_icon.jpg # 网站图标
  type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  darkmode: true # 是否启用暗色主题，可选值（true,false）

imageCDN: # 图片 CDN 功能
  enable: false # 开启该功能  
  origin: /../../images/ # 图片原始目录
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # 图片 CDN 域名
  
# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
# 自带图标库为https://nexmoe.com/lib/iconfont/demo_index.html
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

search: 
  type: local # 可选engine（用搜索引擎搜索）、swiftype、或local（本地搜索）
  # url: https://cn.bing.com/search?q=site:nexmoe.com # 搜索引擎地址，在type为swiftype时无效 e.g:https://www.google.com/search?q={你的博客链接}
  # id: <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效

# cdn: # 这里可以修改站点使用的库的CDN
#   disqusjs: # 从 Disqus API 渲染评论组件
#     css: https://cdn.bootcdn.net/ajax/libs/disqusjs/1.3.0/disqusjs.min.css
#     js: https://cdn.bootcdn.net/ajax/libs/disqusjs/1.3.0/disqus.min.js
#   gitalk: # 基于 Github Issue 和 Preact 的现代评论组件
#     css: https://cdn.bootcdn.net/ajax/libs/gitalk/1.7.2/gitalk.min.css
#     js: https://cdn.bootcdn.net/ajax/libs/gitalk/1.7.2/gitalk.min.js
#   valine: #评论系统
#     js: https://cdn.bootcdn.net/ajax/libs/valine/1.4.16/Valine.min.js
#   justifiedGallery: #画廊 这是一个 JQuery 插件，可让您创建高质量的合理图片库。填满所有空格！
#     js: https://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
#   jquery: #  JavaScript 工具库
#     js: https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js
#   lazysizes: # 用于图像（包括响应式图像）、iframe 和脚本（小部件）的高性能（jankfree）惰性加载器。
#     js: https://cdn.bootcdn.net/ajax/libs/lazysizes/5.3.2/lazysizes.js
#   mdui: # 基于材料设计的 CSS 框架
#     js: https://cdn.bootcdn.net/ajax/libs/mdui/1.0.2/js/mdui.js
#   fancybox: # 支持触控、响应迅速且完全可定制的 jQuery 灯箱脚本
#     js: https://cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.js
#   mathjax: # 开源的 JavaScript 数学显示引擎，适用于所有浏览器。
#     js: https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
#   highlight: #highlightjs 代码高亮
#     css: /libs/css/base16_dracula.min.css

cdn: # 这里可以修改站点使用的库的CDN
  disqusjs: # 从 Disqus API 渲染评论组件
    css: /libs/disqusjs/1.3.0/disqusjs.min.css
    js: /libs/disqusjs/1.3.0/disqus.min.js
  gitalk: # 基于 Github Issue 和 Preact 的现代评论组件
    css: /libs/gitalk/1.7.2/gitalk.min.css
    js: /libs/gitalk/1.7.2/gitalk.min.js
  valine: #评论系统
    js: /libs/valine/1.4.16/Valine.min.js
  justifiedGallery: #画廊 这是一个 JQuery 插件，可让您创建高质量的合理图片库。填满所有空格！
    js: /libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
  jquery: #  JavaScript 工具库
    js: /libs/jquery/3.6.0/jquery.min.js
  lazysizes: # 用于图像（包括响应式图像）、iframe 和脚本（小部件）的高性能（jankfree）惰性加载器。
    # js: https://cdn.bootcdn.net/ajax/libs/lazysizes/5.3.2/lazysizes.js
    js: /libs/lazysizes/5.3.2/lazysizes.js
  mdui: # 基于材料设计的 CSS 框架
    js: /libs/mdui/1.0.2/js/mdui.js
  fancybox: # 支持触控、响应迅速且完全可定制的 jQuery 灯箱脚本
    js: /libs/fancybox/3.5.7/jquery.fancybox.js
  mathjax: # 开源的 JavaScript 数学显示引擎，适用于所有浏览器。
    js: /libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  highlight: #highlightjs 代码高亮
    css: /libs/highlight/css/base16_dracula.min.css


menu:
  回到首页: 
    - /
    - icon-home
  文章归档:  # 使用说明：https://docs.nexmoe.com/article/archive
   - /archive.html
   - icon-container
  近期目标:
    - recentGoal.html
    - icon-Recents
  关于博主:
    - /aboutMe.html
    - icon-aboutme

  # 网站收藏: 
    # - /stars.html # 使用说明：https://docs.nexmoe.com/article/py
    # - icon-star

  
widgets:
- search
- social
- category
- tagcloud
- archive #settings: widgetAchive
- recent_posts
- link #settings: widgetLink

maxTagcloud: 0  # 标签云组件显示的标签数量，0 表示不限制

social:
  # QQ群: 
  #   - https://jq.qq.com/?_wv=1027&k=5CfKHun
  #   - icon-QQ
  #   - rgb(249, 174, 8)
  #   - rgba(249, 174, 8, .1)
  哔哩哔哩:
    - https://space.bilibili.com/73686452
    - icon-bilibili
    - rgb(231, 106, 141)
    - rgba(231, 106, 141,0.1)
  GitHub:
    - https://github.com/YiguiDing
    - icon-github
    - rgb(255, 118, 30)
    - rgba(255, 118, 30,0.1)
  Gitee:
    - https://gitee.com/YiguiDing
    - icon-gitee
    - rgb(255, 185, 0)
    - rgba(255, 185, 0, 0.1)
  微博:
    - https://weibo.com/u/6304917168
    - icon-weibo
    - rgb(51, 213, 122)
    - rgba(51, 213, 122, 0.1)
  知乎:
    - https://zhihu.com/people/ding-yi-gui-90
    - icon-zhihu
    - rgb(14, 135, 234)
    - rgba(14, 135, 234,0.1)
  QQ:
    - 244
    - icon-qq
    - rgb(0, 219, 255)
    - rgba(0, 219, 255, 0.15)

# 自定义样式，启用后可在站点的source文件夹下新建custom.css自定义站点样式
customstyle: false  
color: # 配色方案，从first到seventh为优先级为1-7的颜色，默认为彩虹配色
  first: # 同时作为主题色
    r: 255 
    g: 78
    b: 106
  second:
    r: 255
    g: 118
    b: 30
  third:
    r: 255
    g: 185
    b: 0
  fourth:
    r: 51
    g: 213
    b: 122
  fifth:
    r: 0
    g: 219
    b: 255
  sixth:
    r: 26
    g: 152
    b: 255
  seventh:
    r: 144
    g: 144
    b: 255

# 向搜索引擎验证你对站点的所有权，用于向搜索引擎提交 sitemap 和管理站点被搜索引擎收录的情况。
site_verification: 
  google:
  baidu:

# 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La统计、百度统计
analytics: 
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

# 评论框，目前支持 gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot 使用 false 可以关闭
comment: gitalk
gitalk:
  admin: YiguiDing # 拥有对该repo进行操作的 GitHub username
  owner: YiguiDing # 持有该 repo 的 GitHub username
  repo: yiguiding.github.io # 存放评论的 issue 所在的 repo
  clientID: e0b7de11a5245802f0b0 # GitHub Client ID
  clientSecret: 27f791b72cc246099608bb26bd4972043ebc63b5 # GitHub Client Secret
  pagerDirection: "last" #评论排序方式first时间先后
  language: "zh-CN" #Localization language key, support [en, zh-CN, zh-TW, es-ES, fr, ru, de, pl, ko, fa, ja].
gitment:
  owner: nexmoe # 持有该 repo 的 GitHub username
  repo: nexmoe.github.io # 存放评论的 issue 所在的 repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret
valine: 
  appId: <API_ID> # leancloud application app id
  appKey: <API_Key> # leancloud application app key
disqus:
  shortname: <shortname> # 你的 Disqus shortname
disqusjs:
  shortname: <shortname> # 你的 Disqus shortname
  sitename: <sitename> # 你站点的名称，将会显示在「评论基础模式」的 header 中；该配置应该和 Disqus Admin - Settings - General - Website Name 一致
  api: https://disqus.skk.moe/disqus/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
  apikey: <api_key> # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个；如果你只需要填入一个 API Key，则可以填入 String 或 Array。
  admin: <admin> # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - Settings - Account - Username 获取你的 Username
  adminLabel: <adminLabel> # 你想显示在 Disqus Moderator Badge 中的文字。该配置应和 Disqus Admin - Settings - Community - Moderator Badge Text 相同
changyan:
  appid: <APP_ID> # 畅言的 APPID
  conf: <CONF> # 畅言的 CONF
  thread_key_type: path # 可选 id 或 path
livere:
  data_uid: <data_uid> # 你的来必力 UID，可以在来必力后台获取
DiscussBot:
  id: <id> # 站点id
  comments: 5 # 可能是限制每位用户单页面评论最多条数？
  color: # 评论框主色调
  dislike: 0 # 显示差评按钮
  icons: 0 # 图标主题
  diff: 0 # 每位用户name不同颜色

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'
copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

# achive widget behavior
widgetAchive: #文章归档组件
  archive_type: 'year' #按月展示还是按年展示
  show_count: true  #是否展示数量

widgetLink: #链接组件
  # - title: hhhhh
  #   img : <img_path>
  #   link : <url>
  # - title: <title>
  #   img : <img_path>
  #   link : <url>

# 自定义侧边栏尾部内容
sidebar:
    # '
    #       <br>
    #       <a target="_blank" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral">
    #           <img src="https://i.dawnlab.me/c0268c1e6cfd0863d6ba35be1575941a.png" width="150px">
    #       </a>
    # '
#           <script data-ad-client="ca-pub-2058306854838448" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>'



hexo_calendar:
  enable: true
  width: 810
  height: 160
  id: "calendar"
  monthLang: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
  dayLang: ['周日','周一','周二','周三','周四','周五','周六']
  weeks: 55
  title: "文章更新频率"
  echarts_Lib_URL: https://cdn.staticfile.org/echarts/4.7.0/echarts.min.js
  # echarts_Lib_URL: /libs/echarts/echarts4.7.0.min.js
