title: DYG的个人博客
description: >
  Here is DYG's personal technical blog
  <br>May publish some study notes
  <br>Or just record life
#  <br>Prove to the world that I am still alive
#这里是DYG的个人技术博客
#<br>可能会会发表一些学习笔记
#<br>或者只是单纯记录一下生活
#<br>向世界证明一下自己还活着

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://YiguiDing.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Yigui Ding
author-image:   images/user/head_icon2.jpg
author-job:     “待业青年”
author-email:   2449695354@qq.com # Add your email for contant form.
author-bilibili: 73686452
author-slogan: >
  在绝望中坚持真理 在荒诞中奋起反抗
#用于接收邮件
formspree-POST-URL: https://formspree.io/f/mdobkkgl #action="https://formspree.io/f/mdobkkgl"

#社交账号
social-github:    YiguiDing
social-weibo:     6304917168 #uid
social-bilibili:  73686452   #uid
social-zhihu:     ding-yi-gui-90

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: #UA-99631805-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: Mr-Ding # Add your shortname for Disqus Comment. For example mr-brown

# 网站角标
web_icon_Dir: /images/web_icon/web_icon1.jpg
MD_img_Dir:   /images/文章图片/       #site.MD_img_Dir
# 分类文件
category_dir: category #这个分类是指 /_site/category

#分享链接
share_to_QQ:    https://connect.qq.com/widget/shareqq/index.html?url=
share_to_weibo: https://service.weibo.com/share/share.php?url=
share_to_qzone: https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=
share_to_TieBa: http://tieba.baidu.com/f/commit/share/openShareApi?url=
# Facebook：http://www.facebook.com/sharer.php?u=分享地址
# Twitter ： https://twitter.com/intent/tweet?url=分享地址&via=分享人（可以@）&text=分享内容
# Google+ : https://plus.google.com/share?url=分享地址
# 新浪微博：http://service.weibo.com/share/share.php?url=地址&pic=图片地址&title=标题&appkey=您申请的应用appkey,显示分享来源(可选)&ralateUid=关联用户的UID，分享微博会@该用户(可选)
# 腾讯微博：'http://v.t.qq.com/share/share.php?title='+content+'&url='+url+'&pic='+picurl;
# 百度贴吧：http://tieba.baidu.com/f/commit/share/openShareApi?url=地址&title=标题&desc=描述&pic=图片
# QQ空间：http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey??url=地址&title=标题&pics=图片
# 领英：http://www.linkedin.com/shareArticle?spm= &mini=true&url=地址

markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num/"

include:
  - _pages              #表单和感谢页面
  - search.json         #表单         
  - category            #/category
  - game
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.github
  - Gemfile.flxton
  - vendor
  - LICENSE.txt
  - README.md
  - attachments
