title: DYG的个人博客
description: >
  Here is DYG's personal technical blog
  <br>May publish some study notes
  <br>Or just record life
#  <br>Prove to the world that I am still alive
#这里是DYG的个人技术博客
#<br>可能会会发表一些学习笔记
#<br>或者只是单纯记录一下生活
#<br>向世界证明一下自己还活着

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://YiguiDing.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: "192.168.2.104" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Yigui Ding
author-image:   head_icon.jpg
author-job:     待业青年
author-email:   2449695354@qq.com # Add your email for contant form.
author-bilibili: 73686452
#author-twitter: YiguiDing # Add your twitter account
# author-weiboUid: 6304917168 # Add your twitter account
formspree-Id: mdobkkgl #action="https://formspree.io/f/mdobkkgl"
author-slogan: >
  在绝望中坚持真理 在荒诞中奋起反抗

# Social settings
# social-twitter:   YiguiDing
# social-facebook:
social-github:    YiguiDing
social-weibo:     6304917168 #uid
social-bilibili:  73686452   #uid
social-zhihu:     ding-yi-gui-90
# social-pinterest: YiguiDing
# social-instagram: YiguiDing
# social-youtube:
# social-vk:   
# social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: #UA-99631805-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: Mr-Ding # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
category_dir: category #这个分类是指 /_site/category

markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num/"

include:
  - _pages              #表单和感谢页面
  - search.json     
  - category            #这个分类是指/中的分类 在这里的意思是把/category 拷贝到/_site/category 
#当在本地测试时会创建/_site/category 上传github时需手动将其拷贝到/category

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE.txt
  - README.md
