server:
  address: 0.0.0.0
  port: 8080

jetcache:
  # statIntervalMinutes: 15
  # areaInCacheName: false
  local:
    default:
      type: linkedhashmap #other choose：caffeine
      keyConvertor: fastjson #other choose： fastjson2/fastjson/jackson
  #     limit: 100
  # remote:
  #   default:
  #     type: redis
  #     host: 172.30.64.71
  #     port: 6379
  #     poolConfig:
  #       minIdle: 5
  #       maxIdle: 20
  #       maxTotal: 50
  #   simArea: 
  #     type: redis
  #     host: 172.30.64.71
  #     port: 6379
  #     poolConfig:
  #       minIdle: 5
  #       maxIdle: 20
  #       maxTotal: 50
  #     # keyConvertor: fastjson2 #other choose：fastjson/jackson
  #     # broadcastChannel: projectA
  #     # valueEncoder: java #other choose：kryo/kryo5
  #     # valueDecoder: java #other choose：kryo/kryo5