server:
  address: 0.0.0.0
  port: 8080


spring:
  redis:
    host: 172.30.64.71
    port: 6379
  cache:
    type:
      redis
    redis:
      use-key-prefix: true # 是否将key作为前缀
      key-prefix: perfix_ # key前缀的前缀
      cache-null-values: false # Allow caching null values.
      time-to-live: 60s # 存活时间