name: Deploy blog

on:
  push:
    branches:
      - master

jobs:
  deploy-static-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Build Blog
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: static-pages
          folder: src/.vuepress/dist

  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-static-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: static-pages
          fetch-depth: 0

      - name: Configuration environment
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh-keyscan dingdingdang.online >> ~/.ssh/known_hosts
          git config --global user.name 'YiguiDing'
          git config --global user.email '2449695354@qq.com'
          ssh git@dingdingdang.online "git config --global --add safe.directory /var/www/vuepress2-blog-root/"
          ssh git@dingdingdang.online "git config --global --add receive.denyCurrentBranch ignore"
          git push -f git@dingdingdang.online:/var/www/vuepress2-blog-root/ static-pages
          ssh git@dingdingdang.online "cd /var/www/vuepress2-blog-root/  && git reset --hard HEAD"
